milk_app/urls.py
from django.urls import path
from milk_app import views


##CHANGE IT UP - IMPORTANT TO HAVE REFERENCES FOR URLS.
app_name = 'milk_app'



urlpatterns = [
    
    path('', views.home, name = 'home'),
    path('about/', views.about, name = 'about'),
    path('support/contact_us/', views.contactPage, name = 'contact'),
    path('listing/<slug:listing_id_slug>', views.show_listing, name="show_listing"),
    path('add_listing/', views.add_listing, name='add_listing'),
    path('browse_listings/', views.browse_listings, name = 'browse_listings'),
    path('my_listings/', views.my_listings, name = "my_listings"),
    path('FAQ/', views.faq, name = "FAQ"),
    path('careers/', views.careers, name = "careers"),
    path('purchase/<slug:listing_id_slug>', views.purchase_listing, name = "purchase_listing"),
    path('remove/<slug:listing_id_slug>', views.remove_listing, name = "remove_listing"),
    path('rate/<slug:listing_id_slug>', views.rate_listing, name = "rate_listing"),
    path('cancel/<slug:listing_id_slug>', views.cancel_listing, name = "cancel_listing"),

    path ('profile/', views.user_profile, name = "profile"),

    #Registration
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register' ),
    path('login/', views.user_login, name='login'),
]

milkstudents/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from milk_app import views
from django.urls import reverse



urlpatterns = [
    path('', views.home, name ='home'),
    path('admin/', admin.site.urls),
    
    path('milk_app/', include('milk_app.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

milk_app/forms.py
from typing import Optional
from django import forms
from django.forms.fields import ImageField
from django.forms.widgets import Textarea
from milk_app.models import Listing, UserProfile
from django.contrib.auth.models import User
import datetime

# class CategoryForm(forms.ModelForm):
#     name = forms.CharField(max_length = Category.NAME_MAX_LENGTH, help_text="Please enter the category name.")
#     views = forms.IntegerField(widget=forms.HiddenInput(), initial = 0)
#     likes = forms.IntegerField(widget = forms.HiddenInput(), initial= 0)
#     slug = forms.CharField(widget = forms.HiddenInput(), required = False)

#     class Meta:
#         model = Category
#         fields = ('name', )
    
# class PageForm(forms.ModelForm):
#     title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
#     url = forms.URLField(max_length=Page.TITLE_MAX_LENGTH, help_text="Please enter the URL of the page.")
#     views = forms.IntegerField(widget = forms.HiddenInput(), initial = 0)

#     class Meta:
#         model = Page
#         exclude = ('category', )

#     def clean(self):
#         cleaned_data = self.cleaned_data
#         url = cleaned_data.get('url')

#         if url and not url.startswith('http://'):
#             url = f'http://{url}'
#             cleaned_data['url'] = url

#         return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput(attrs = {'placeholder' : 'Password'}))
    password_confirm = forms.CharField(widget = forms.PasswordInput(attrs = {'placeholder' : 'Confirm Password'}))
    username = forms.CharField(widget = forms.TextInput(attrs = {'placeholder' : 'Enter your Username'}))
    email = forms.EmailField(widget = forms.TextInput(attrs = {'placeholder' : 'Enter your Email'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class LoginForm(forms.ModelForm):
    username = forms.CharField(widget = forms.TextInput(attrs = {'placeholder' : 'Enter your Username'}))
    password = forms.CharField(widget = forms.PasswordInput(attrs = {'placeholder' : 'Password'}))
    
    class Meta:
        model = User
        fields = ('username', 'password')

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('account',)  
        exclude = ('picture',)


class ListingForm(forms.ModelForm):

    
    name = forms.CharField(max_length = 40, widget = forms.TextInput(attrs = {'placeholder' : 'Name your listing'}), label= "Listing name")
    description = forms.CharField(max_length= 500, widget = forms.Textarea(attrs = {'placeholder' : 'Describe your listing'}), label = "Description")
    #price = forms.IntegerField(widget=forms.HiddenInput(),required = False)
    address = forms.CharField(max_length = 100, widget = forms.TextInput(attrs = {'placeholder' : 'Apparment, studio, or floor'}))
    university = forms.CharField(max_length= 40, widget = forms.TextInput(attrs = {'placeholder' : 'Which Univeristy is the lisiting relevant to'}), label = "Univeristy name")
    
    price = forms.DecimalField(max_digits=6, decimal_places=2, widget = forms.TextInput(attrs = {'placeholder' : 'Price in £'}))
    
    picture = forms.ImageField(label = 'Select a file')
    
    
    slug = forms.SlugField(widget=forms.HiddenInput(), required = False)

    class Meta:
        model = Listing
        fields = ('name','description','address','university','price','picture')
        exclude = ('user', 'rating', 'date', 'listing_id')

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(widget = forms.TextInput(attrs = {'placeholder' : 'Enter your Email'}))

    class Meta:
        model = User
        fields = ('username', 'email',)


class UserProfileUpdateForm(forms.ModelForm):
    picture = forms.ImageField(widget=forms.FileInput, label = "Update your profile image", error_messages = {'invalid':("Image files only")}, required = False)


    class Meta:
        model = UserProfile
        fields = ('picture',)


class UpdateListingForm(forms.ModelForm):
    name = forms.CharField(max_length = 40, widget = forms.TextInput(attrs = {'placeholder' : 'Enter a new name for your listing'}), label= "Listing name", required= True)
    description = forms.CharField(max_length= 500, widget = forms.Textarea(attrs = {'placeholder' : 'Describe your listing'}), label = "Description")
    picture = forms.ImageField(widget=forms.FileInput, label = "Update the listing's image", error_messages = {'invalid':("Image files only")}, required = False)

    class Meta:
        model = Listing
        fields = ('name','price', 'description', 'picture',)    

milk_app/views.py
from milk_app.models import Listing, UserProfile
from django.shortcuts import render
from django.http import HttpResponse
from milk_app.forms import ListingForm, UpdateListingForm, UserForm, UserProfileForm, UserProfileUpdateForm, UserUpdateForm, LoginForm
from django.shortcuts import redirect
from django.urls import reverse 
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
import uuid
from django.contrib import messages
from django.db.models import Q
domains = [".edu",".ac.uk",".ac.nz", ".student","@student"] 
# Create your views here.
# Homepage for starters - nothing interesting
def home(request):

    context_dict = {}

    return render(request, 'milk_app/home.html', context=context_dict)

def about(request):
    
    context_dict = {}
    
    response = render(request, 'milk_app/about.html',context = context_dict)
    return response

def contactPage(request):
    context_dict = {}
    response = render(request, 'milk_app/contact_us.html',context = context_dict)
    return response
def careers(request):
    context_dict = {}
    response = render(request, 'milk_app/careers.html',context = context_dict)
    return response
def faq (request):
    context_dict = {}
    response = render(request, 'milk_app/FAQ.html',context = context_dict)
    return response

def register(request):
    registered = False
    

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        
        role = profile_form['account'].value()
        email = user_form['email'].value()
           
        ##CHECK FOR UNI EMAIL DOMAIN
        if role == "Tenant" and not any(x in email for x in domains):                
            user_form.add_error('email', 'Please enter a valid University email address')

        elif user_form.is_valid() and user_form.cleaned_data['password'] == user_form.cleaned_data['password_confirm'] and profile_form.is_valid():
            
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            
            profile.save()
            registered = True
            login(request,user)
            messages.success(request, 'Registration Succesful!')
            return redirect(reverse('milk_app:home'))

        elif user_form.cleaned_data['password'] != user_form.cleaned_data['password_confirm']:
             user_form.add_error('password_confirm', 'The passwords do not match - please enter 2 matching passwords')
        else:
            print(user_form.errors, profile_form.errors)
    
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    
    return render(request, 'milk_app/register.html', context={'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):
    context_dict = {}
    login_form = LoginForm()

    if request.method == 'POST':
        login_form = LoginForm(request.POST)

        username = login_form['username'].value()
        password = login_form['password'].value()

        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            messages.success(request, 'Login succesful!')
            return redirect(reverse('milk_app:home'))
        else:
            login_form.add_error(None, "Incorrect details provided - Please try again")
    
        print(login_form.errors)
    
    return render(request, 'milk_app/login.html', {"login_form" : login_form})

def show_listing(request, listing_id_slug):
    update_form = UpdateListingForm()
    
    context_dict = {}
    try:
        #listing object reference
        listing = Listing.objects.get(slug = listing_id_slug)
        
        if listing.userPrev: ##IF THERE IS A SECOND USER - PURCHASE DID HAPPEN
            context_dict['purchased'] = True
        else: ##OTHERWISE THERE ISNT
            context_dict['purchased'] = False

        ### UPDATE LISTING CODE ###
        if request.method == 'POST':
            update_form = UpdateListingForm(request.POST, request.FILES, instance = listing)

        if update_form.is_valid():
            #push update to database
            update_form.save(commit=True)
            
        else:
            update_form = UpdateListingForm(instance = listing)
            
            print(update_form.errors)
    
        owner = listing.user #pass owner data into context dict

        context_dict['listing'] = listing
        context_dict['updated_listing'] = update_form

    except Listing.DoesNotExist:
        context_dict['listing'] = None

    return render(request, 'milk_app/listing.html', context = context_dict)



@login_required
def purchase_listing(request, listing_id_slug): #know for a fact its tenant
    # type = request.POST.get('paymentMethod')

    buyer = request.user.userprofile

    listing = Listing.objects.get(slug = listing_id_slug)
    #keep track of previous owner
    listing.userPrev = listing.user

    #update the owner of the listing 
    listing.user = buyer

    
    #update date
    #listing.date = datetime.now
    listing.save()
    messages.success(request, 'Listing Purchased succesfully!')

    return redirect(reverse('milk_app:my_listings'))

@login_required
def remove_listing(request, listing_id_slug): #know for a fact its tenant
    #Delete the object from db completely
    Listing.objects.get(slug = listing_id_slug).delete()

    messages.success(request, 'Listing removed succesfully')
    return redirect(reverse('milk_app:my_listings'))

@login_required
def rate_listing(request, listing_id_slug): #know for a fact its tenant
    
    listing = Listing.objects.get(slug = listing_id_slug)

    submitted_rating = request.POST.get('star')

    #increment count by 1
    listing.ratingCount = listing.ratingCount + 1
    #update the total 
    listing.ratingTotal = listing.ratingTotal + int(submitted_rating)
    #update the actual
    listing.ratingCurrent = (listing.ratingTotal / listing.ratingCount)

    listing.save()

    messages.success(request, 'Listing rated succesfully!')

    return redirect(reverse('milk_app:browse_listings'))

@login_required
def cancel_listing(request, listing_id_slug): #know for a fact its tenant
    
    listing = Listing.objects.get(slug = listing_id_slug)

    realOwner = listing.userPrev

    #transfer ownership back to tenant
    listing.user = realOwner
    #set userprev to none since no more transfership needed
    listing.userPrev = None

    listing.save()

    messages.success(request, 'Lease cancelled succesfully!')

    return redirect(reverse('milk_app:browse_listings'))


@login_required
def add_listing(request):
    form = ListingForm()

    if request.method == 'POST':
        form = ListingForm(request.POST, request.FILES)

        if form.is_valid():
            
            listing = form.save(commit=False)
            listing.user = request.user.userprofile
            #Generate
            listing.listing_id = uuid.uuid4().hex
            listing.save()

            messages.success(request, 'Listing added succesfully')
            return redirect(reverse('milk_app:my_listings'))
        else:
            print(form.errors)

    return render(request, 'milk_app/add_listing.html', {'listing_form': form})


def browse_listings(request):
    context_dict = {}
    listings = Listing.objects.filter(user__account = "Host")

    if request.method == 'POST': #if user searching for smthn
        try:
            search = request.POST.get('search')
            listings = listings.filter(university__icontains = search)
            context_dict['search'] = search
            context_dict['searched'] = True   
        except:
            context_dict['searched'] = False
        
    ##Only Tenants listings should be visible
    
    context_dict['listings'] =listings
    
    return render(request, 'milk_app/browse_listings.html', context_dict)

@login_required
def my_listings(request):
    #request.user.userprofile

    user_p = request.user.userprofile
    
    context_dict = {}
    my_listings = Listing.objects.filter(Q(user = user_p) |Q(userPrev = user_p))

    context_dict['my_listings'] = my_listings
    context_dict['profile'] = user_p

    return render(request, 'milk_app/my_listings.html', context_dict)

@login_required
def user_profile(request):
    context_dict = {}
    user = request.user
    user_profile = request.user.userprofile

    p_form = UserProfileUpdateForm()
    u_form = UserUpdateForm()

    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance = user)
        p_form = UserProfileUpdateForm(request.POST,request.FILES, instance = user_profile)

    if p_form.is_valid() and u_form.is_valid():
        u_form.save(commit = True)
        p_form.save(commit = True)
        messages.success(request, 'Profile updated succesfully!')
        return redirect(reverse('milk_app:profile'))
    
    else:
        
        u_form = UserUpdateForm(instance=user)
        p_form = UserProfileUpdateForm(instance=user_profile)
        print(p_form.errors, u_form.errors)
    
    context_dict['p_form'] = p_form
    context_dict['u_form'] = u_form


    return render(request, 'milk_app/profile.html',context = context_dict)


@login_required
def user_logout(request):
    logout(request)

    messages.success(request, 'Logged out Succesfully!')

    return redirect(reverse('milk_app:home'))

templates/milk_app/add_listing.html
<!DOCTYPE html>

{% extends 'milk_app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}

    Add a Listing

{% endblock %}

{% block body_block %}
<br><br><br>
<div class="text-center"></div>
    <form  id="listing_form" method="post" action="{% url 'milk_app:add_listing' %}" enctype="multipart/form-data">  
        {% csrf_token %}

        {{ listing_form|crispy }}

        <button class = "btn btn-outline-dark btn-lg" type="submit" name="submit"> Create listing </button>
    </form>
</div>


{% endblock %}

templates/milk_app/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/stylesheet.css' %}">
    <title>
        Milk - {% block title_block %}Milk Students{% endblock %}
    </title>
</head>

<body data-spy="scroll" data-target="#navbarResponsive">

    <!-- Start of the home section -->
    <div id="home">

        <!-- NAVIGATION -->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">

                    <li class="nav-item">
                        <!-- Home reference-->
                        <a class="nav-link" href="{% url 'milk_app:home' %}">HOME</a> <!-- home page -->
                    </li>

                    <li class="nav-item">
                        <!-- About page reference-->
                        <a class="nav-link" href="{% url 'milk_app:about' %}">ABOUT US</a><!-- about page -->
                    </li>

                    <!-- if the user is already logged in he can either view his profile or log out of his account -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'milk_app:FAQ' %}">FAQ</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <!-- Logout if user authenticated reference-->
                        <a class="nav-link" href="{% url 'milk_app:logout' %}">Log out</a>
                    </li>
                    <li class="nav-item">
                        <!-- View profile if user authenticated reference-->
                        <a class="nav-link" href="{% url 'milk_app:profile' %}">View Profile</a>
                    </li>

                    <!-- if the user is not logged in he gets options to either register or log into his account -->
                    {% else %}
                    <li class="nav-item">
                        <!-- Register if user not authenticated reference-->
                        <a class="nav-link" href="{% url 'milk_app:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <!-- Log in if user not authenticated reference-->
                        <a class="nav-link" href="{% url 'milk_app:login' %}">Log in</a>
                    </li>

                    {% endif %}
                    {% if messages %}
                    <li class="nav-item">
                        {% for message in messages %}
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                        <a class="nav-link" id="status" href="#">{{ message }}</a>
                        <script>
                            setTimeout(() => { document.getElementById("status").remove() }, 4000)
                        </script>
                        {% endfor %}

                </ul>
                </li>
                {% endif %}
                </ul>
            </div>
        </nav>
    </div>

    {% block body_block %}{% endblock %}

    <footer class="page-footer bg-dark">
        <div class="container offset">
            <div class="row justify-content-center">

                <div class="col-md-4 text-center my-auto">
                    <img src="{% static 'images/logo.jpg' %}">
                    <p class="mb-4">
                        Worked on this project over the couple of last weeks in a team of mostly two people. Hopefully
                        it
                        helps finding you the student accomodation you want and you really deserve!</p>
                </div>

                <div class="col-md-4 text-center">
                    <p class="mb-4">
                        <span class="icon-phone d-block h4 text-primary"></span>
                    </p>
                    <h1>Authors:</h1><br>

                    <h3>Artem Grechushkin</h3>
                    <a href="https://github.com/Kowalifwer">github<img src="{% static 'images/github.svg' %}"></a>, <a
                        href="https://www.instagram.com/artgrech/">instagram<img
                            src="{% static 'images/instagram.png' %}"></a>
                    <br>
                    <h3>Oliver Alan Štafurik</h3>
                    <a href="https://github.com/stafino">github<img src="{% static 'images/github.svg' %}"></a>, <a
                        href="https://www.instagram.com/oliverstafurik/">instagram<img
                            src="{% static 'images/instagram.png' %}"></a>
                    <br>
                    <p class="mini">Gunraj Gulati</p> <br>
                    <!-- the thing is Xiao did absolutely nothing. We haven't heard from her since the design spec and even back then she was with us for like 12 minutes before deadline no more. -->
                </div>

                <div class="col-md-4 text-center">
                    <p>
                        <span class="icon-room d-block h4 text-primary"></span>
                    <h3>Based in Glasgow, United Kingdom </h3>
                    </p>
                    <iframe
                        src="https://maps.google.com/maps?q=University%20of%20Glasgow%20Glasgow%20G12%208QQ,%20United%20Kingdom&t=&z=13&ie=UTF8&iwloc=&output=embed"
                        width="330" height="200" frameborder="0" style="border:0;margin-top:-27px;height: 250px;"
                        allowfullscreen=""></iframe>
                </div>

            </div>
        </div>
    </footer>


    </div>
    </div>
    </div>

    <!-- Bootstrap core JavaScript -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP"
        crossorigin="anonymous"></script>
    <script src="{% static  'js/global.js' %}" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP"
        crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/cferdinandi/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>


    <!-- I had to leave these scripts in-line, was trying to put them to the global.js but could not get it to work. All the others that did work
            were left in the global.js file.-->

    <!-- SMOOTH SCROLL PLUGIN -->
    <script>
        var scroll = new SmoothScroll('a[href*="#"]', {
            speed: 1500,
            speedAsDuration: true
        });
    </script>

    <!-- script for scalable carousel captions weeee -->
    <script>
        $(document).ready(function () {
            $('.carousel .carousel-caption').css('zoom', $('.carousel').width() / 1250);
        });

        $(window).resize(function () {
            $('.carousel .carousel-caption').css('zoom', $('.carousel').width() / 1250);
        });
    </script>

</body>

</html>

templates/milk_app/browse_listings.html
<!DOCTYPE html>
{% extends 'milk_app/base.html' %}

{% load static %} 


{% block title_block %}
    Browse Listings
    

{% endblock %}

{% block body_block %}
<br><br>
<h1 class="top-space-heading">Browse all available accomododation</h1>

    <div class="text-center">
        
        {% if not searched %}
                <h4>Popular listings:</h4>
            {% else %}
                <h4>Listings relevant to your search: '{{search}}'</h4>
        {% endif %}

        {% if listings %}
                    
            
        <div class="row">
            {% for l in listings  %}
            
                <div class="col-sm-6">
                <a href = "{% url 'milk_app:show_listing' l.slug %}">
                  <div class="card">
                    
                    <img src="/media/{{l.picture}}" class="card-img-top" alt="...">
                    
                    <div class="card-body">
                        <h5 class="card-title">{{ l.name }}</h5>
                
                        <p class="card-text">Located near {{ l.university }}</p>
                        <p class="card-text">Property rating: {{ l.ratingCurrent }} (based on {{ l.ratingCount }} reviews)</p>
                    </div>  
                  </div>
                </a>
                </div>
            {% endfor %}
            </div>
            
    
        {% else %}       
            <h2> No Relevant listings available</h2>

        {% endif %}
        <br><br><br><br><br>
        Would you like to search for a listing near a specific university?
        <form id = "search" action = "{% url 'milk_app:browse_listings'%}" method = "post">
            {% csrf_token %}
            <label for="search"> University name: </label>
            <input id="search_field" type="text" name="search" value="{{ search }}" placeholder="eg. University of Glasgow">
            <br>
            <button class = "btn btn-outline-dark btn-sm" type="submit"> Search! </button>
        </form>
        
    </div>
        
    
    
{% endblock %}

templates/milk_app/login.html
{% extends 'milk_app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<h1 class="top-space-heading">Login to MilkStudents</h1>

{% if user.is_authenticated %}
<strong>You have been successfully registered!</strong>


<a href="{% url 'milk_app:profile'%}">Check out your profile</a><br />


{% else %}

<div class="text-center">
    
    <img class="mb-4" src="{% static 'images/logo.jpg' %}" alt="" width="72" height="72">
    <form id="login_form" method="post" action="{% url 'milk_app:login' %}">
        {% csrf_token %}
        
        {{ login_form|crispy }}

        <button class = "btn btn-outline-dark btn-lg" type="submit" name="submit"> Log in </button>
    </form>
</div>



{% endif %}



<!-- <style>
    #login_form input {
        background-color: brown !important;
    }
</style> -->
    
{% endblock %}

templates/milk_app/my_listings.html
<!DOCTYPE html>
{% extends 'milk_app/base.html' %}

{% load static %} 


{% block title_block %}
    Browse my Listings
    

{% endblock %}

{% block body_block %}
<br><br>    
<h1 class="top-space-heading">Browse your listings</h1>

    <div class="text-center">       
            {% if profile.account == 'Host' %}
                <p> All the listings that you are currently renting out:</p>
            {% elif profile.account == 'Tenant' %}
                <p>All the listings that you are currently renting:</p>
            {% endif %}


            {% if my_listings %} 

            <div class="row">
            {% for l in my_listings  %}
            
                <div class="col-sm-6">
                <a href = "{% url 'milk_app:show_listing' l.slug %}">
                  <div class="card">
                    
                    <img src="/media/{{l.picture}}" class="card-img-top" alt="...">
                    
                    <div class="card-body">
                        <h5 class="card-title">{{ l.name }}</h5>
                
                        <p class="card-text">Located near {{ l.university }}</p>
                        <p class="card-text">Property rating: {{ l.ratingCurrent }} (based on {{ l.ratingCount }} reviews)</p>
                    </div>  
                  </div>
                </a>
                </div>
            {% endfor %}
            </div>
                    
                 
            {% else %}       
                <p> YOU HAVE NO LISTINGS</p>
                {% if profile.account == 'Host' %}
                <a href = "{% url 'milk_app:add_listing' %}"> Add a listing </a>
                {% endif %}

            {% endif %}
            
            
        
    </div>
    
{% endblock %}